include theos/makefiles/common.mk

LIBRARY_NAME = Basic
Basic_FILES = Basic.m GlobalBasic.m
Basic_FRAMEWORKS = UIKit
Basic_PRIVATE_FRAMEWORKS = GraphicsServices

ADDITIONAL_CFLAGS = -std=c99

include $(THEOS_MAKE_PATH)/library.mk
